"""
SQLAlchemy Database Models for SupportNova
"""
from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Float, Boolean, DateTime, ForeignKey, JSON
from backend.database.db import Base

class UserModel(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String(255), unique=True, index=True, nullable=False)
    full_name = Column(String(255), nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role = Column(String(50), nullable=False, default="Customer")  # Customer, Agent, Reviewer, Manager, Admin
    created_at = Column(DateTime, default=datetime.utcnow)

class ComplaintModel(Base):
    __tablename__ = "complaints"

    id = Column(Integer, primary_key=True, index=True)
    complaint_number = Column(String(50), unique=True, index=True, nullable=False)
    customer_email = Column(String(255), nullable=False)
    customer_name = Column(String(255), nullable=False)
    account_number = Column(String(100), nullable=True)
    title = Column(String(255), nullable=False)
    category = Column(String(100), nullable=False)
    sub_category = Column(String(100), nullable=True)
    description = Column(Text, nullable=False)
    status = Column(String(50), nullable=False, default="Submitted")
    priority = Column(String(50), nullable=False, default="Medium")
    assigned_department = Column(String(100), nullable=True)
    assigned_agent = Column(String(255), nullable=True)
    
    sentiment_score = Column(Float, nullable=True, default=0.5)
    genai_summary = Column(Text, nullable=True)
    genai_suggested_response = Column(Text, nullable=True)
    genai_confidence = Column(Float, nullable=True, default=0.85)
    
    python_validation_passed = Column(Boolean, default=True)
    python_validation_flags = Column(JSON, nullable=True, default=list)
    has_hallucination = Column(Boolean, default=False)
    hallucination_details = Column(Text, nullable=True)
    
    requested_credit = Column(Float, nullable=True, default=0.0)
    approved_credit = Column(Float, nullable=True, default=0.0)
    resolution_notes = Column(Text, nullable=True)
    
    # Pipeline 1 tracking fields
    pipeline1_status = Column(String(50), nullable=False, default="unprocessed")  # unprocessed | processing | completed | failed
    pipeline1_failure_reason = Column(Text, nullable=True)
    genai_analysis_result = Column(JSON, nullable=True)
    
    # Pipeline 2 tracking fields
    pipeline2_status = Column(String(50), nullable=False, default="unprocessed")  # unprocessed | schema_invalid | completed | failed
    pipeline2_failure_reason = Column(Text, nullable=True)
    python_verification_report = Column(JSON, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


class VerificationReportModel(Base):
    """Stored Verification Reports generated by Pipeline 2 Comparison Engine."""
    __tablename__ = "verification_reports"

    id = Column(Integer, primary_key=True, index=True)
    complaint_id = Column(String(100), nullable=False, index=True)
    verification_score = Column(Float, nullable=False)
    final_status = Column(String(50), nullable=False)  # Verified | Manual Review Required
    pipeline2_status = Column(String(50), nullable=False, default="completed")
    field_comparisons = Column(JSON, nullable=False, default=dict)
    mismatches = Column(JSON, nullable=False, default=list)
    unsupported_promises = Column(JSON, nullable=False, default=list)
    hallucinated_claims = Column(JSON, nullable=False, default=list)
    contradictions = Column(JSON, nullable=False, default=list)
    overwritten_fields = Column(JSON, nullable=False, default=dict)
    created_at = Column(DateTime, default=datetime.utcnow)


class KnowledgeDocumentModel(Base):
    __tablename__ = "kb_documents"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(String(50), unique=True, index=True, nullable=False)
    title = Column(String(255), nullable=False)
    category = Column(String(100), nullable=False)
    version = Column(String(20), default="1.0")
    status = Column(String(20), default="Active")
    effective_date = Column(String(50), nullable=False)
    expiry_date = Column(String(50), nullable=True)
    file_name = Column(String(255), nullable=False)
    file_path = Column(String(255), nullable=False)
    content_hash = Column(String(64), unique=True, index=True, nullable=False)
    content = Column(Text, nullable=True)
    tags = Column(String(255), nullable=True)
    # Document processing status fields
    parsing_status = Column(String(20), default="pending", nullable=False)  # pending | processing | completed | failed
    parsing_error = Column(Text, nullable=True)
    chunk_count = Column(Integer, nullable=True, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)


class KBChunkModel(Base):
    """Semantic chunks extracted from knowledge base documents."""
    __tablename__ = "kb_chunks"

    id = Column(Integer, primary_key=True, index=True)
    chunk_id = Column(String(50), unique=True, index=True, nullable=False)
    document_id = Column(String(50), nullable=False, index=True)
    section = Column(String(50), nullable=True)
    heading = Column(String(255), nullable=True)
    page_reference = Column(Integer, nullable=True)
    version = Column(String(20), nullable=True, default="1.0")
    text = Column(Text, nullable=False)
    word_count = Column(Integer, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

class RuleMatrixModel(Base):
    __tablename__ = "rule_matrix"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String(50), unique=True, index=True, nullable=False)
    category = Column(String(100), nullable=False, index=True)
    subcategory = Column(String(100), nullable=False, index=True)
    conditions = Column(JSON, nullable=False, default=dict)
    department = Column(String(100), nullable=False, index=True)
    supporting_departments = Column(JSON, nullable=True, default=list)
    urgency = Column(String(50), nullable=False)
    priority = Column(String(50), nullable=False)
    policy_id = Column(String(50), ForeignKey("kb_documents.document_id"), nullable=False)
    escalation_required = Column(Boolean, default=False, nullable=False)
    escalation_level = Column(String(50), nullable=True)
    required_actions = Column(JSON, nullable=False, default=list)
    prohibited_actions = Column(JSON, nullable=False, default=list)
    follow_up_required = Column(Boolean, default=False, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    created_by = Column(String(255), nullable=False, default="admin@nexalink.com")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class RuleMatrixAuditModel(Base):
    """Audit log tracking creation, edits, and soft-deletions of rule matrix items."""
    __tablename__ = "rule_matrix_audit"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String(50), nullable=False, index=True)
    action = Column(String(50), nullable=False)  # CREATE | UPDATE | DEACTIVATE
    previous_state = Column(JSON, nullable=True)
    new_state = Column(JSON, nullable=True)
    changed_by = Column(String(255), nullable=False)
    changed_at = Column(DateTime, default=datetime.utcnow)

class RuleMatchLogModel(Base):
    """Audit log capturing every execution match attempt by RuleMatrixEngine."""
    __tablename__ = "rule_match_log"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String(50), nullable=True)
    complaint_features = Column(JSON, nullable=False)
    matched = Column(Boolean, default=False)
    matched_at = Column(DateTime, default=datetime.utcnow)


class KBVersionAuditModel(Base):
    """Immutable audit trail for Knowledge Base document status and version transitions."""
    __tablename__ = "kb_version_audit"

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(String(50), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    category = Column(String(100), nullable=False)
    previous_status = Column(String(50), nullable=True)
    new_status = Column(String(50), nullable=False)
    previous_version = Column(String(50), nullable=True)
    new_version = Column(String(50), nullable=False)
    changed_at = Column(DateTime, default=datetime.utcnow)
    changed_by = Column(String(255), nullable=False)
    reason = Column(Text, nullable=True)

class AuditLogModel(Base):
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    complaint_number = Column(String(50), nullable=True)
    action = Column(String(100), nullable=False)
    performed_by = Column(String(255), nullable=False)
    details = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)


class PromptTemplateModel(Base):
    """Versioned prompt templates for GenAI Pipeline."""
    __tablename__ = "prompt_templates"

    id = Column(Integer, primary_key=True, index=True)
    template_id = Column(String(100), unique=True, index=True, nullable=False)
    name = Column(String(100), nullable=False, index=True)
    version = Column(String(20), nullable=False, default="v1")
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    is_active = Column(Boolean, default=True, nullable=False)


class GenAICallLogModel(Base):
    """Prompt version logging for every GenAI API call."""
    __tablename__ = "genai_call_log"

    id = Column(Integer, primary_key=True, index=True)
    prompt_template_id = Column(String(100), nullable=False)
    prompt_version = Column(String(20), nullable=False)
    provider = Column(String(50), nullable=False, default="anthropic")
    model_name = Column(String(100), nullable=False)
    request_timestamp = Column(DateTime, default=datetime.utcnow)
    response_timestamp = Column(DateTime, default=datetime.utcnow)
    context_references = Column(JSON, nullable=True, default=list)
    status = Column(String(50), nullable=False, default="success")
    error_details = Column(Text, nullable=True)


class GenAIAnalysisLogModel(Base):
    """Analysis results log for Pipeline 1."""
    __tablename__ = "genai_analysis_log"

    id = Column(Integer, primary_key=True, index=True)
    complaint_id = Column(String(100), nullable=False, index=True)
    prompt_version = Column(String(20), nullable=False)
    model = Column(String(100), nullable=False)
    raw_response = Column(Text, nullable=False)
    parsed_result = Column(JSON, nullable=True)
    pipeline1_status = Column(String(50), nullable=False, default="completed")  # completed | failed
    failure_reason = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)


